# Site settings
title: Matthew Taylor's Blog
header-img: img/home-bg.jpg
email: matthewtylr@gmail.com
description: "A blog about analytics, bioinformatics, disease, and soccer."
baseurl: ""
url: "www.matthewtylr.com"
twitter_username: mataytay7
github_username:  matthewtylr
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
